[package]
name = "streamer-3d-rust-testapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
streamer_3d_rust = { path = "../streamer-3d-rust" }